// document metadata
= Final Project
Joby M. Anthony III <jmanthony1@liberty.edu>; Carson W. Farmer <cfarmer6@liberty.edu>
:affiliation: PhD Students
:document_version: 1.0
:revdate: April 27, 2022
// :description: 
// :keywords: 
:imagesdir: {docdir}/ENGR-527_727-WeCANDoIt-Final_Project
:bibtex-file: ENGR-527_727-WeCANDoIt-Final_Project.bib
:toc: auto
:xrefstyle: short
:sectnums: |,all|
:chapter-refsig: Chap.
:section-refsig: Sec.
:stem: latexmath
:eqnums: AMS
:stylesdir: C:/Users/cfarmer6/Documents/GitHub/WeCANDoIt/Asciidoc/Document/
:stylesheet: asme.css
:noheader:
:nofooter:
:docinfodir: C:/Users/cfarmer6/Documents/GitHub/WeCANDoIt/Asciidoc/Document/
:docinfo: private
:front-matter: any
:!last-update-label:

// example variable
// :fn-1: footnote:[]

// Python modules
<%!
    from engineering_notation import EngNumber as engr
    import numpy as np
%>
// end document metadata





// begin document
[abstract]
.Abstract
As the consumption of sugary carbonated drinks has increased in recent years, an overwhelming number of aluminum cans have entered waste disposal facilities. To reduce the spatial requirement of the individual cans, we propose a rotationally driven high-throughput can crushing device that operates either via human or machine power to easily deform cans to at least 20% of the original volume. By utilizing a varying thickness wheel, the rotation of the wheel compresses the can against the wall of the device to less than 20% of the volume. The shaft is constructed from AISI 316 while the crushing wheel is cast stainless steel. A finite element study was conducted to validate that the stresses experienced in the design did not surpass the yield stresses of the components. The proposed device solves the issue of crushing cans and allows for automatic reloading to allow for continued operation. 
cite:[uguralAdvancedMechanicsMaterials2019]
// *Keywords:* _{keywords}_



[#sec-intro, {counter:secs}]
== Introduction
:!subs:
:!figs:
:!tabs:

[#sec-development, {counter:development}]
== Development of Engineering Specifications

[#sec-synthesis, {counter:synthesis}]
== Sythesis of the Design

[#sec-design, {counter:design}]
== Deisgn Analysis and Optimization

[#sec-conclusions, {counter:conclusions}]
== Conclustions

// [appendix#sec-appendix-Figures]
// == Figures



[bibliography]
== Bibliography
bibliography::[]
// end document





// that's all folks